name: build and deploy

on:
  workflow_dispatch:
    inputs:
      data:
        description: "env"
        required: true
        default: "null"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: bip
          POSTGRES_PASSWORD: Production_123
          POSTGRES_DB: db
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: run install
        run: bun install

      # Step 2: Save SSH key and set permissions
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set strict permissions for the private key
          ls -la ~/.ssh
          echo "SSH key saved successfully!"

      # Step 3: Add known hosts to avoid host key verification prompt
      - name: Add known hosts
        run: |
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set appropriate permissions for known_hosts
          echo "Known hosts added successfully!"

      - name: run index.ts
        run: |
          bun run index.ts --data ${{ inputs.data }} --key ${{ secrets.WIBU_GIT_TOKEN }} --vps-host ${{ secrets.VPS_HOST }} --vps-user ${{ secrets.VPS_USER }} --vps-key ~/.ssh/id_rsa

      - name: set data upload
        run: |
          echo "$(cat data-upload.txt)" >> $GITHUB_ENV

      # Deploy to a new version directory
      - name: Deploy to VPS (New Version)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ~/.ssh/id_rsa
          source: "${{ env.DIR_SOURCE }}"
          target: "${{ env.DIR_TARGET }}"
