name: ngetest bun global

on:
  workflow_dispatch:
    inputs:
      key:
        description: "env"
        required: true
        default: "null"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Save SSH key and set permissions
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set strict permissions for the private key
          ls -la ~/.ssh
          echo "SSH key saved successfully!"

      # Step 3: Add known hosts to avoid host key verification prompt
      - name: Add known hosts
        run: |
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set appropriate permissions for known_hosts
          echo "Known hosts added successfully!"

      # Step 4: Connect to the server
      - name: Connect to server
        run: |
          echo "Attempting to connect to VPS..."
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} -o StrictHostKeyChecking=no -t "ls -la ~"