name: test connect server
on:
  workflow_dispatch:
    inputs:
      secret:
        description: "secret"
        required: false
        default: "null"
      env:
        description: "env"
        required: false
        default: "null"
      host:
        description: "host"
        required: true
        default: "null"
      username:
        description: "username"
        required: true
        default: "null"
      key:
        description: "key"
        required: true
        default: "null"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: find port
        run: |
          PORT=$(curl -s -X GET https://wibu-bot.wibudev.com/api/find-port | jq -r '.[0]')
          if [ -z "$PORT" ] || ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
            echo "Invalid or missing port from API."
            exit 1
          fi
          echo "APP_PORT=$PORT" >> $GITHUB_ENV

      - name: test connect server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          key: ${{ inputs.key }}
          script: |
            echo "lihat port diserver"
            echo "${{ env.APP_PORT }}"
            echo "${{ github.run_id }}"
