name: test connect server
on:
  workflow_dispatch:
    inputs:
      secret:
        description: "secret"
        required: false
        default: "null"
      env:
        description: "env"
        required: false
        default: "null"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test connect server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ls -a
