name: test connect server
on:
  workflow_dispatch:
    inputs:
      secret:
        description: "secret"
        required: false
        default: "null"
      env:
        description: "env"
        required: false
        default: "null"
      host:
        description: "host"
        required: true
        default: "null"
      username:
        description: "username"
        required: true
        default: "null"
      key:
        description: "key"
        required: true
        default: "null"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test connect server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          key: ${{ inputs.key }}
          script: |
            ls -a
