name: log

on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Handle WIBU_DATA
        run: echo "WIBU_DATA=${{ secrets.WIBU_GIT_TOKEN }}[x]${{ secrets.FIREBASE }}[x]${{ inputs.data }}[x]${{ secrets.WIBU_KEY }}" >> $GITHUB_ENV

      - name: Handle env
        run: bun run handle-env.ts --data ${{ env.WIBU_DATA }}

      - name: Check log on VPS server
        id: server-log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Jalankan pm2 logs selama 5 detik dan simpan output ke file sementara
            timeout 5s pm2 logs ${{ env.WIBU_NAMESPACE }} > /tmp/${{ env.WIBU_NAMESPACE }}.txt 2>&1 || true

            # Baca isi file log dan kirim ke stdout
            LOG_CONTENT=$(cat /tmp/${{ env.WIBU_NAMESPACE }}.txt)
            echo "::set-output name=log_content::$LOG_CONTENT"
        env:
          WIBU_NAMESPACE: ${{ env.WIBU_NAMESPACE }}

      - name: Print log
        run: echo "${{ toJson(steps.server-log) }}"