name: log

on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Handle WIBU_DATA
        run: echo "WIBU_DATA=${{ secrets.WIBU_GIT_TOKEN }}[x]${{ secrets.FIREBASE }}[x]${{ inputs.data }}[x]${{ secrets.WIBU_KEY }}" >> $GITHUB_ENV

      - name: Handle env
        run: bun run handle-env.ts --data ${{ env.WIBU_DATA }}

      - name: Check log on VPS server
        id: vps-check # Tambahkan ID untuk referensi step
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "RESULT=thi is from server" > /tmp/result.txt
            cat /tmp/result.txt
        # Output dari script akan ditangkap oleh GitHub Actions

      - name: Capture RESULT
        run: |
          echo "Hasil dari VPS: ${{ steps.vps-check.outputs.stdout }}"
          echo "RESULT=${{ steps.vps-check.outputs.stdout }}" >> $GITHUB_ENV

      - name: Use RESULT
        run: |
            echo "Nilai RESULT yang didapat: ${{ env.RESULT }}"