name: log

on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Handle WIBU_DATA
        run: echo "WIBU_DATA=${{ secrets.WIBU_GIT_TOKEN }}[x]${{ secrets.FIREBASE }}[x]${{ inputs.data }}[x]${{ secrets.WIBU_KEY }}" >> $GITHUB_ENV

      - name: Handle env
        run: bun run handle-env.ts --data ${{ env.WIBU_DATA }}
    
      - name: Handle WIBU_DATA
        run: |
          # Write the SSH key to a file
          cat <<EOF > ./id_rsa
            ${{ secrets.VPS_KEY }}
          EOF
      
          # Set correct permissions for the SSH key
          chmod 600 ./id_rsa
      
          # Debugging: Verify the SSH key file
          echo "SSH key written to ./id_rsa"
          ls -l ./id_rsa
      
          # Run the TypeScript script with the required data
          # bun run actions/ssh.ts --data "${{ secrets.VPS_USER }}[x]${{ secrets.VPS_HOST }}"
