name: test jalankan obake
on:
  workflow_dispatch:
    inputs:
      data:
        description: "data yang diperlukan"
        required: true
        default: "null"

env:
  WA_PHONE: "6289697338821,6289697338822"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: config env
        run: |
          echo "${{ inputs.data }}" > .env
          source .env

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: bun install
        run: |
          bun install

      - name: clone repo
        run: |
          source .env
          git clone https://x-access-token:${TOKEN}@github.com/bipproduction/${REPO}.git
          tree -I node_modules -L 4

      - name: repo installation
        run: |
          cd $REPO
          bun install
          tree -I node_modules -L 4
