name: test jalankan obake
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (e.g., staging, production)"
        required: true
        default: "staging"
      version:
        description: "Version to deploy"
        required: false
        default: "latest"
env:
  WA_PHONE: "6289697338821,6289697338822"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout kode sumber
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Step 2: Install tree (if not already installed)
      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      # Step 3: Kirim notifikasi ke API build Start
      - name: Notify start build
        run: |
          bun install
          cat cp /home/runner/work/_temp/_github_workflow/event.json
          cp /home/runner/work/_temp/_github_workflow/*.log all_logs.txt
          cat all_logs.txt
