name: Build And Save Log

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Target environment (e.g., staging, production)"
        required: true
        default: "{}"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
       # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .bun
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Step 3: Kirim notifikasi ke API build Start
      - name: Notify start build
        run: |
          IFS=',' read -ra PHONES <<< "${{ env.WA_PHONE }}"
          for PHONE in "${PHONES[@]}"; do
            ENCODED_TEXT=${{ inputs.data }}
            curl -X GET "https://wa.wibudev.com/code?text=$ENCODED_TEXT&nom=$PHONE"
          done
