name: ngetest bun global
on:
  workflow_dispatch:
    inputs:
      key:
        description: "env"
        required: true
        default: "null"
      data_required:
        description: "data"
        required: true
        default: "null"
      data_extend:
        description: "data"
        required: true
        default: "null"
jobs:
  coba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: coba
        run: |
          bun install
          bun run index.ts --key "${{ inputs.key }}" --data-required "${{ inputs.data_required }}" --data-extend "${{ inputs.data_extend }}"
