name: ngetest bun global
on:
  workflow_dispatch:
    inputs:
      key:
        description: "env"
        required: true
        default: "null"
      data_required:
        description: "data"
        required: true
        default: "null"
      data_extend:
        description: "data"
        required: true
        default: "null"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: bip
          POSTGRES_PASSWORD: Production_123
          POSTGRES_DB: db
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Install scp
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: jalankan
        run: |
          scp --version
          # bun install
          # bun run index.ts --key "${{ inputs.key }}" --data-required "${{ inputs.data_required }}" --data-extend "${{ inputs.data_extend }}"
