name: test jalankan obake
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (e.g., staging, production)"
        required: true
        default: "staging"
      version:
        description: "Version to deploy"
        required: false
        default: "latest"
env:
  WA_PHONE: "6289697338821,6289697338822"
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "pwd"
          POSTGRES_DB: "db"
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout kode sumber
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Kirim notifikasi ke API build Start
      - name: Notify start build
        run: |
          IFS=',' read -ra PHONES <<< "${{ env.WA_PHONE }}"
          for PHONE in "${PHONES[@]}"; do
            ENCODED_TEXT="apa kabarnya dini dari obake"
            curl -X GET "https://wa.wibudev.com/code?text=$ENCODED_TEXT&nom=$PHONE"
          done
