name: ngetest bun global
on:
  workflow_dispatch:
    inputs:
      env:
        description: "env"
        required: true
        default: "null"
      local:
        description: "app"
        required: true
        default: "null"
jobs:
  coba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: coba
        run: |
          bun install
          mkdir -p assets
          echo ${{ inputs }} > assets/data-local.json
          bun index.ts
