name: ngetest bun global
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install

      - name: run test
        run: bun run index_test.ts