name: process list

on:
  workflow_dispatch:
    inputs:
      data:
        description: "data"
        required: true
        default: "null"

jobs:
  collect-process-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Handle env
        run: |
          cat <<EOF > ./id_rsa
          ${{ secrets.VPS_KEY }}
          EOF

          chmod 600 ./id_rsa

      - name: run collect process list
        run: |
            ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "pm2 jlist" > list.txt

            ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "cat /etc/nginx/conf.d/wibudev.conf" > wibudev.conf.txt

            ssh -o StrictHostKeyChecking=no -i ./id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "cat /etc/nginx/conf.d/muku.conf" > muku.conf.txt

            grep -oE '\[[^{]*({.*})\]' list.txt > clean_list.txt

            cat clean_list.txt | bun run lib/send-notify.ts \
            --data ${{ secrets.FIREBASE }}[x]${{ secrets.WIBU_KEY }} \
            --ref "/process/list/data/process"

            cat wibudev.conf.txt | bun run lib/send-notify.ts \
            --data ${{ secrets.FIREBASE }}[x]${{ secrets.WIBU_KEY }} \
            --ref "/process/list/data/wibudev"

            cat muku.conf.txt | bun run lib/send-notify.ts \
            --data ${{ secrets.FIREBASE }}[x]${{ secrets.WIBU_KEY }} \
            --ref "/process/list/data/muku"