name: test workflow
on:
 push:
    branches:
      - test
 pull_request:
    branches:
      - test
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: coba
      run: |
       rsync --version
